import { Achievement, AchievementCategory, AchievementTier, RewardType } from '../src/types';

// This data was previously in a remote file and has been reconstructed here to fix a loading error.
export const ACHIEVEMENTS_DATA: Omit<Achievement, 'check'>[] = [
  // --- Generation --- 🎵
  { id: 'gen_first_song', name: "Premier Hit", description: "Générer votre première chanson.", tier: AchievementTier.Bronze, category: AchievementCategory.Generation, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 25, description: "25 Crédits" } },
  { id: 'gen_10_songs', name: "Artiste Prolifique", description: "Générer 10 chansons.", tier: AchievementTier.Bronze, category: AchievementCategory.Generation, isSecret: false, target: 10, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" } },
  { id: 'gen_50_songs', name: "Machine à Hits", description: "Générer 50 chansons.", tier: AchievementTier.Silver, category: AchievementCategory.Generation, isSecret: false, target: 50, reward: { type: RewardType.Credits, value: 150, description: "150 Crédits" } },
  { id: 'gen_100_songs', name: "Légende du Studio", description: "Générer 100 chansons.", tier: AchievementTier.Gold, category: AchievementCategory.Generation, isSecret: false, target: 100, reward: { type: RewardType.Credits, value: 300, description: "300 Crédits + Titre : Légende du Studio" } },
  { id: 'gen_all_modes', name: "Touche-à-tout", description: "Utiliser chaque mode de génération au moins une fois.", tier: AchievementTier.Silver, category: AchievementCategory.Generation, isSecret: false, target: 5, reward: { type: RewardType.Credits, value: 75, description: "75 Crédits" } },
  { id: 'gen_multilingual_3', name: "Polyglotte", description: "Générer des chansons dans au moins 3 langues différentes.", tier: AchievementTier.Silver, category: AchievementCategory.Generation, isSecret: false, target: 3, reward: { type: RewardType.Credits, value: 60, description: "60 Crédits" } },
  { id: 'gen_viking_tongue', name: "Skáld", description: "Générer une chanson en féroïen ou en vieux norrois.", tier: AchievementTier.Gold, category: AchievementCategory.Generation, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 100, description: "100 Crédits + Titre : Skáld" } },
  { id: 'gen_queen_rhapsody', name: "Mama, ooooh...", description: "Utiliser la structure 'Rhapsodie Opératique' de Queen.", tier: AchievementTier.Silver, category: AchievementCategory.Generation, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 40, description: "40 Crédits" } },

  // --- Exploration --- 🔍
  { id: 'explore_analyzer', name: "Musicologue", description: "Analyser une chanson avec l'Analyseur.", tier: AchievementTier.Bronze, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits (remboursement partiel)" } },
  { id: 'explore_editor_image', name: "Retoucheur d'Images", description: "Modifier une pochette d'album avec l'Éditeur.", tier: AchievementTier.Bronze, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 20, description: "20 Crédits" } },
  { id: 'explore_rhyme_dictionary', name: "Le Mot Juste", description: "Utiliser le dictionnaire de rimes dans l'Éditeur de paroles.", tier: AchievementTier.Bronze, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 15, description: "15 Crédits" } },
  { id: 'explore_special_trait', name: "Sparkle", description: "Utiliser une Caractéristique Spéciale d'artiste pour la première fois.", tier: AchievementTier.Silver, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 30, description: "30 Crédits" } },
  { id: 'explore_quick_prompt', name: "Inspiration Divine", description: "Utiliser la barre d'Inspiration Instantanée.", tier: AchievementTier.Bronze, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 10, description: "10 Crédits" } },
  { id: 'explore_advanced_structure', name: "Architecte Sonore", description: "Créer et utiliser une structure de chanson personnalisée.", tier: AchievementTier.Silver, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" } },
  { id: 'explore_random_bg', name: "Nouveau Paysage", description: "Générer un arrière-plan aléatoire dans les paramètres.", tier: AchievementTier.Bronze, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 10, description: "10 Crédits" } },
  { id: 'explore_marketing_kit', name: "Attaché de Presse", description: "Générer un Kit Marketing pour une de vos chansons.", tier: AchievementTier.Gold, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 150, description: "150 Crédits (remboursement partiel)" } },
  { id: 'explore_song_burst', name: "Producteur en Série", description: "Utiliser la génération de chansons en rafale (x3) pour la première fois.", tier: AchievementTier.Gold, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 100, description: "100 Crédits (remboursement partiel)" } },
  { id: 'explore_album_art_burst', name: "Directeur Artistique en Série", description: "Utiliser la génération de pochettes en rafale (x4).", tier: AchievementTier.Silver, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 100, description: "100 Crédits (remboursement partiel)" } },
  { id: 'explore_personalized_training', name: "Signature Sonore", description: "Utiliser le mode de génération 'Personnalisé' (IA-Training) pour la première fois.", tier: AchievementTier.Gold, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 200, description: "200 Crédits (remboursement partiel)" } },
  
  // --- Collection --- 📚
  { id: 'collection_5_artists', name: "Collectionneur Éclectique", description: "Générer des chansons inspirées par 5 artistes différents.", tier: AchievementTier.Bronze, category: AchievementCategory.Collection, isSecret: false, target: 5, reward: { type: RewardType.Credits, value: 30, description: "30 Crédits" } },
  { id: 'collection_15_artists', name: "Discographie Variée", description: "Générer des chansons inspirées par 15 artistes différents.", tier: AchievementTier.Silver, category: AchievementCategory.Collection, isSecret: false, target: 15, reward: { type: RewardType.Credits, value: 80, description: "80 Crédits" } },
  { id: 'collection_30_artists', name: "Maître des Influences", description: "Générer des chansons inspirées par 30 artistes différents.", tier: AchievementTier.Gold, category: AchievementCategory.Collection, isSecret: false, target: 30, reward: { type: RewardType.Credits, value: 200, description: "200 Crédits + Titre : Maître des Influences" } },
  { id: 'collection_5_covers', name: "Directeur Artistique", description: "Générer 5 pochettes d'album.", tier: AchievementTier.Bronze, category: AchievementCategory.Collection, isSecret: false, target: 5, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" } },
  { id: 'collection_25_covers', name: "Galerie d'Art", description: "Générer 25 pochettes d'album.", tier: AchievementTier.Silver, category: AchievementCategory.Collection, isSecret: false, target: 25, reward: { type: RewardType.Credits, value: 150, description: "150 Crédits" } },
  
  // --- Mastery --- 🏆
  { id: 'mastery_eminem_all_traits', name: "Rap God", description: "Générer une chanson d'Eminem avec ses 4 Caractéristiques Spéciales activées.", tier: AchievementTier.Gold, category: AchievementCategory.Mastery, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 100, description: "100 Crédits + Titre : Rap God" } },
  { id: 'mastery_fusion', name: "Alchimiste Musical", description: "Générer une chanson en mode Artiste en fusionnant avec au moins 3 styles additionnels.", tier: AchievementTier.Silver, category: AchievementCategory.Mastery, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 60, description: "60 Crédits" } },
  { id: 'mastery_unlock_all_bronze', name: "Collectionneur de Bronze", description: "Débloquer tous les succès de tier Bronze.", tier: AchievementTier.Gold, category: AchievementCategory.Mastery, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 200, description: "200 Crédits" } },
  { id: 'mastery_unlock_all_silver', name: "Collectionneur d'Argent", description: "Débloquer tous les succès de tier Argent.", tier: AchievementTier.Diamond, category: AchievementCategory.Mastery, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 500, description: "500 Crédits + Titre : Collectionneur d'Argent" } },

  // --- Prestige --- 👑
  { id: 'prestige_ultimate_member', name: "Membre Ultimate", description: "Soutenir Lyr-IA en souscrivant au plan Ultimate.", tier: AchievementTier.Diamond, category: AchievementCategory.Prestige, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 300, description: "300 Crédits + Titre : Mécène" } },
  { id: 'prestige_annual_member', name: "Vision à Long Terme", description: "Souscrire à n'importe quel plan annuel.", tier: AchievementTier.Gold, category: AchievementCategory.Prestige, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 150, description: "150 Crédits" } },

  // --- Secrets & Easter Eggs --- 🎁
  { id: 'secret_customize_theme', name: "Artiste Visuel", description: "Personnaliser le thème de couleurs de l'application.", tier: AchievementTier.Bronze, category: AchievementCategory.Exploration, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 15, description: "15 Crédits" } },
  { id: 'secret_daft_punk_robot', name: "Technologic", description: "Générer une chanson de Daft Punk avec les traits 'Voix Vocoder' et 'Chant Robotique' activés.", tier: AchievementTier.Gold, category: AchievementCategory.Exploration, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 100, description: "100 Crédits" } },
  { id: 'easter_egg_bohemian_rhapsody', name: "Is this the real life?", description: "Demander une certaine rhapsodie bohémienne.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" } },
  { id: 'easter_egg_808s_heartbreak', name: "Heartless", description: "Générer une chanson sur un cœur brisé et une certaine boîte à rythmes.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" } },
  { id: 'easter_egg_master_of_puppets', name: "Master of Puppets", description: "Créer une structure personnalisée de 15 parties ou plus.", tier: AchievementTier.Gold, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 80, description: "80 Crédits" } },
  { id: 'easter_egg_rhyme_orange', name: "Eminem serait fier", description: "Essayer de trouver une rime pour le mot 'orange'.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 40, description: "40 Crédits" } },
  { id: 'easter_egg_all_about_the_hook', name: "Au Cœur du Refrain", description: "Créer une structure personnalisée composée uniquement de 4 refrains.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 25, description: "25 Crédits" } },
  { id: 'easter_egg_acid_house', name: "Acid House", description: "Faire une requête rapide mentionnant les boîtes à rythmes TB-303 et TR-808/909.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" } },
  { id: 'easter_egg_sound_check', name: "Sound Check", description: "Jouer frénétiquement avec le bouton 'Amplifier le Style Prompt'.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 20, description: "20 Crédits" } },
  { id: 'easter_egg_studio_tour', name: "Studio Tour", description: "Visiter les onglets Générateur, Analyseur et Éditeur, puis revenir au Générateur.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 15, description: "15 Crédits" } },
  { id: 'easter_egg_franco_viking', name: "Franco-Viking", description: "Générer une chanson de Vígundr en français.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" } },
  { id: 'easter_egg_lofi_beats', name: "Lofi Beats to Relax/Study to", description: "Générer un instrumental Lo-fi, Chillwave et Jazz.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 30, description: "30 Crédits" } },
  { id: 'easter_egg_konami_code', name: "↑↑↓↓←→←→BA", description: "Entrer un certain code secret très connu.", tier: AchievementTier.Gold, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 100, description: "100 Crédits" } },
  { id: 'easter_egg_logo_spam', name: "Spammeur de Logo", description: "Cliquer sur le logo de manière un peu trop insistante.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 20, description: "20 Crédits" } },
  { id: 'easter_egg_sandwich', name: "sudo make me a sandwich", description: "Demander poliment un sandwich à l'IA.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 25, description: "25 Crédits" } },
  { id: 'easter_egg_hidden_pixel', name: "Œil de Lynx", description: "Trouver et cliquer sur le pixel secret dans le guide.", tier: AchievementTier.Gold, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 150, description: "150 Crédits" } },
  { id: 'easter_egg_over_9000', name: "IT'S OVER 9000!", description: "Faire une requête qui dépasse un certain niveau de puissance.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" } },
  { id: 'easter_egg_all_your_base', name: "All Your Base Are Belong to Us", description: "Faire une référence à un classique de l'internet.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 25, description: "25 Crédits" } },
  { id: 'easter_egg_man_machine', name: "Mensch-Maschine", description: "Générer une chanson de Kraftwerk sur le thème de l'Homme-Machine.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" } },
  { id: 'easter_egg_theme_spammer', name: "Caméléon", description: "Changer de thème de couleur de manière compulsive.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 20, description: "20 Crédits" } },
  { id: 'easter_egg_number_of_the_beast', name: "The Number of the Beast", description: "Demander à Iron Maiden une chanson sur un certain nombre.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" } },
  { id: 'easter_egg_rickroll', name: "Never Gonna Give You Up", description: "Vous connaissez les règles, et moi aussi.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" } },
];
