import { AnimeTheme } from '../src/types';

export const ANIME_THEMES: AnimeTheme[] = [
    { name: 'Aggretsuko', styles: 'J-Pop, Death Metal, Comedy' },
    { name: 'Attack on Titan', styles: 'Symphonic Metal, Epic Rock, Choral' },
    { name: 'Baccano!', styles: 'Big Band Jazz, Swing, Ragtime' },
    { name: 'Berserk', styles: 'Heavy Metal, Industrial Rock, Dark Ambient' },
    { name: 'Black Butler', styles: 'Gothic Rock, Classical, Darkwave' },
    { name: 'Bleach', styles: 'J-Rock, J-Pop, Alternative Rock' },
    { name: 'Bocchi the Rock!', styles: 'J-Rock, Alternative Rock, Indie Rock' },
    { name: 'Chainsaw Man', styles: 'J-Rock, Alternative Rock, Electronic' },
    { name: 'Code Geass', styles: 'J-Rock, Alternative Rock' },
    { name: 'Cowboy Bebop', styles: 'Jazz, Blues, Bebop, Rock' },
    { name: 'Cyberpunk: Edgerunners', styles: 'Synthwave, Electronic, Alternative' },
    { name: 'Death Note', styles: 'Alternative Metal, Hard Rock' },
    { name: 'Demon Slayer', styles: 'J-Pop, Symphonic Rock, Traditional Japanese' },
    { name: 'Devilman Crybaby', styles: 'Techno, Electronic, Dark Ambient, Industrial' },
    { name: 'Dragon Ball Z', styles: 'J-Rock, Hard Rock, Power Metal' },
    { name: 'Durarara!!', styles: 'J-Rock, Alternative, Urban, Jazz-hop' },
    { name: 'Ergo Proxy', styles: 'Trip Hop, Industrial, Ethereal Wave' },
    { name: 'Fairy Tail', styles: 'Celtic Rock, Folk Metal, Orchestral' },
    { name: 'FLCL (Fooly Cooly)', styles: 'Alternative Rock, J-Rock, Garage Rock' },
    { name: 'Fruits Basket', styles: 'J-Pop Ballad, Acoustic, Soft Pop' },
    { name: 'Fullmetal Alchemist: Brotherhood', styles: 'J-Rock, Pop Rock' },
    { name: 'Ghost in the Shell', styles: 'Electronic, Ambient, Traditional Japanese' },
    { name: 'Gurren Lagann', styles: 'J-Rock, Orchestral, Hip Hop, Epic' },
    { name: 'Haikyuu!!', styles: 'J-Rock, Pop Punk, Hype' },
    { name: 'Hunter x Hunter', styles: 'J-Pop, J-Rock, Adventure' },
    { name: 'Initial D', styles: 'Eurobeat, Techno' },
    { name: 'JoJo\'s Bizarre Adventure', styles: 'Rock, Funk, Pop, Electronic' },
    { name: 'Jujutsu Kaisen', styles: 'J-Rock, Alternative Rock, Hip Hop' },
    { name: 'K-On!', styles: 'J-Pop, Pop Rock, Slice of Life' },
    { name: 'Kill la Kill', styles: 'J-Rock, Electronic, Orchestral, Hype' },
    { name: 'Lucky Star', styles: 'J-Pop, Denpa Song, Moe' },
    { name: 'Macross Frontier', styles: 'J-Pop, Anisong, Electronic, Pop Rock' },
    { name: 'Made in Abyss', styles: 'Orchestral, Ambient, Ethereal, Dark Fantasy' },
    { name: 'Mob Psycho 100', styles: 'J-Rock, Funk Rock, Psychedelic' },
    { name: 'Monogatari Series', styles: 'J-Pop, Electronic, Experimental, Ambient' },
    { name: 'Mushishi', styles: 'Ambient, Traditional Japanese, Minimalist' },
    { name: 'Mushoku Tensei: Jobless Reincarnation', styles: 'Orchestral, Folk, Fantasy, Ambient' },
    { name: 'My Hero Academia', styles: 'J-Rock, Pop Punk, Alternative Rock' },
    { name: 'Naruto', styles: 'J-Rock, Hip Hop, Traditional Japanese' },
    { name: 'Neon Genesis Evangelion', styles: 'J-Pop, Classical, Ballad' },
    { name: 'Odd Taxi', styles: 'Hip Hop, Jazz-hop, Lo-fi, City Pop' },
    { name: 'One Piece', styles: 'J-Pop, Rock, Ska, Adventure Orchestral' },
    { name: 'One-Punch Man', styles: 'J-Rock, Heavy Metal' },
    { name: 'Paranoia Agent', styles: 'Electronic, Experimental, Psychedelic' },
    { name: 'Promare', styles: 'Electronic, EDM, Hyperpop, Rock' },
    { name: 'Psycho-Pass', styles: 'Electronic, Industrial, Darkwave' },
    { name: 'Puella Magi Madoka Magica', styles: 'J-Pop, Classical, Dark Ambient, Magical Girl' },
    { name: 'Re:Zero', styles: 'Symphonic Rock, J-Pop, Dark Fantasy' },
    { name: 'Sailor Moon', styles: 'J-Pop, City Pop, Symphonic Pop' },
    { name: 'Samurai Champloo', styles: 'Lo-fi Hip Hop, Nujabes-style Jazz Hop' },
    { name: 'Serial Experiments Lain', styles: 'Ambient, Electronic, Trip Hop, Cyberpunk' },
    { name: 'Sonny Boy', styles: 'Indie Rock, Alternative, Electronic, Ambient' },
    { name: 'Spy x Family', styles: 'Jazz, Swing, J-Pop, City Pop' },
    { name: 'Steins;Gate', styles: 'J-Pop, Sci-fi Electronic' },
    { name: 'Sword Art Online', styles: 'J-Rock, Electronic, Orchestral' },
    { name: 'The Melancholy of Haruhi Suzumiya', styles: 'J-Pop, Rock, Dance' },
    { name: 'Tokyo Ghoul', styles: 'Alternative Rock, Post-hardcore, Metalcore' },
    { name: 'Violet Evergarden', styles: 'Orchestral, Classical, Emotional, Ballad' },
    { name: 'Vinland Saga', styles: 'Folk Rock, Epic Orchestral, Nordic Folk' },
    { name: 'Your Lie in April', styles: 'Classical Piano, Orchestral, J-Pop Ballad' },
];
