import { Achievement, AchievementCategory, AchievementTier, RewardType, TitleColor } from '../src/types';

// This data was previously in a remote file and has been reconstructed here to fix a loading error.
export const ACHIEVEMENTS_DATA: Omit<Achievement, 'check'>[] = [
  // --- Generation --- 🎵
  { id: 'gen_first_song', name: "Premier Hit", description: "Générer votre première chanson.", tier: AchievementTier.Bronze, category: AchievementCategory.Generation, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 25, description: "25 Crédits" }, icon: "🎤" },
  { id: 'gen_10_songs', name: "Artiste Prolifique", description: "Générer 10 chansons.", tier: AchievementTier.Bronze, category: AchievementCategory.Generation, isSecret: false, target: 10, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" }, icon: "🎸" },
  { id: 'gen_50_songs', name: "Machine à Hits", description: "Générer 50 chansons.", tier: AchievementTier.Silver, category: AchievementCategory.Generation, isSecret: false, target: 50, reward: { type: RewardType.Credits, value: 150, description: "150 Crédits" }, icon: "🎹" },
  { id: 'gen_100_songs', name: "Légende du Studio", description: "Générer 100 chansons.", tier: AchievementTier.Gold, category: AchievementCategory.Generation, isSecret: false, target: 100, reward: { type: RewardType.Title, value: "Légende du Studio", description: "Titre : Légende du Studio", titleColor: TitleColor.Purple }, icon: "👑" },
  { id: 'gen_all_modes', name: "Touche-à-tout", description: "Utiliser chaque mode de génération au moins une fois.", tier: AchievementTier.Silver, category: AchievementCategory.Generation, isSecret: false, target: 5, reward: { type: RewardType.Credits, value: 75, description: "75 Crédits" }, icon: "🎭" },
  { id: 'gen_multilingual_3', name: "Polyglotte", description: "Générer des chansons dans au moins 3 langues différentes.", tier: AchievementTier.Silver, category: AchievementCategory.Generation, isSecret: false, target: 3, reward: { type: RewardType.Credits, value: 60, description: "60 Crédits" }, icon: "🌍" },
  { id: 'gen_viking_tongue', name: "Skáld", description: "Générer une chanson en féroïen ou en vieux norrois.", tier: AchievementTier.Gold, category: AchievementCategory.Generation, isSecret: false, target: 1, reward: { type: RewardType.Title, value: "Skáld", description: "Titre : Skáld", titleColor: TitleColor.Purple }, icon: "⚔️" },
  { id: 'gen_queen_rhapsody', name: "Mama, ooooh...", description: "Utiliser la structure 'Rhapsodie Opératique' de Queen.", tier: AchievementTier.Silver, category: AchievementCategory.Generation, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 40, description: "40 Crédits" }, icon: "👨‍🎤" },

  // --- Exploration --- 🔍
  { id: 'explore_analyzer', name: "Musicologue", description: "Analyser une chanson avec l'Analyseur.", tier: AchievementTier.Bronze, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits (remboursement partiel)" }, icon: "🔬" },
  { id: 'explore_editor_image', name: "Retoucheur d'Images", description: "Modifier une pochette d'album avec l'Éditeur.", tier: AchievementTier.Bronze, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 20, description: "20 Crédits" }, icon: "🎨" },
  { id: 'explore_rhyme_dictionary', name: "Le Mot Juste", description: "Utiliser le dictionnaire de rimes dans l'Éditeur de paroles.", tier: AchievementTier.Bronze, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 15, description: "15 Crédits" }, icon: "📖" },
  { id: 'explore_special_trait', name: "Sparkle", description: "Utiliser une Caractéristique Spéciale d'artiste pour la première fois.", tier: AchievementTier.Silver, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 30, description: "30 Crédits" }, icon: "✨" },
  { id: 'explore_quick_prompt', name: "Inspiration Divine", description: "Utiliser la barre d'Inspiration Instantanée.", tier: AchievementTier.Bronze, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 10, description: "10 Crédits" }, icon: "💡" },
  { id: 'explore_advanced_structure', name: "Architecte Sonore", description: "Créer et utiliser une structure de chanson personnalisée.", tier: AchievementTier.Silver, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" }, icon: "🏗️" },
  { id: 'explore_random_bg', name: "Nouveau Paysage", description: "Générer un arrière-plan aléatoire dans les paramètres.", tier: AchievementTier.Bronze, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 10, description: "10 Crédits" }, icon: "🖼️" },
  { id: 'explore_marketing_kit', name: "Attaché de Presse", description: "Générer un Kit Marketing pour une de vos chansons.", tier: AchievementTier.Gold, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 150, description: "150 Crédits (remboursement partiel)" }, icon: "📰" },
  { id: 'explore_song_burst', name: "Producteur en Série", description: "Utiliser la génération de chansons en rafale (x3) pour la première fois.", tier: AchievementTier.Gold, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 100, description: "100 Crédits (remboursement partiel)" }, icon: "⚡" },
  { id: 'explore_album_art_burst', name: "Directeur Artistique en Série", description: "Utiliser la génération de pochettes en rafale (x4).", tier: AchievementTier.Silver, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 100, description: "100 Crédits (remboursement partiel)" }, icon: "🎬" },
  { id: 'explore_personalized_training', name: "Signature Sonore", description: "Utiliser le mode de génération 'Personnalisé' (IA-Training) pour la première fois.", tier: AchievementTier.Gold, category: AchievementCategory.Exploration, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 200, description: "200 Crédits (remboursement partiel)" }, icon: "🧬" },
  
  // --- Collection --- 📚
  { id: 'collection_5_artists', name: "Collectionneur Éclectique", description: "Générer des chansons inspirées par 5 artistes différents.", tier: AchievementTier.Bronze, category: AchievementCategory.Collection, isSecret: false, target: 5, reward: { type: RewardType.Credits, value: 30, description: "30 Crédits" }, icon: "🎼" },
  { id: 'collection_15_artists', name: "Discographie Variée", description: "Générer des chansons inspirées par 15 artistes différents.", tier: AchievementTier.Silver, category: AchievementCategory.Collection, isSecret: false, target: 15, reward: { type: RewardType.Credits, value: 80, description: "80 Crédits" }, icon: "💿" },
  { id: 'collection_30_artists', name: "Maître des Influences", description: "Générer des chansons inspirées par 30 artistes différents.", tier: AchievementTier.Gold, category: AchievementCategory.Collection, isSecret: false, target: 30, reward: { type: RewardType.Title, value: "Maître des Influences", description: "Titre : Maître des Influences", titleColor: TitleColor.Purple }, icon: "🎵" },
  { id: 'collection_5_covers', name: "Directeur Artistique", description: "Générer 5 pochettes d'album.", tier: AchievementTier.Bronze, category: AchievementCategory.Collection, isSecret: false, target: 5, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" }, icon: "📀" },
  { id: 'collection_25_covers', name: "Galerie d'Art", description: "Générer 25 pochettes d'album.", tier: AchievementTier.Silver, category: AchievementCategory.Collection, isSecret: false, target: 25, reward: { type: RewardType.Credits, value: 150, description: "150 Crédits" }, icon: "🖌️" },
  
  // --- Mastery --- 🏆
  { id: 'mastery_eminem_all_traits', name: "Rap God", description: "Générer une chanson d'Eminem avec ses 4 Caractéristiques Spéciales activées.", tier: AchievementTier.Gold, category: AchievementCategory.Mastery, isSecret: false, target: 1, reward: { type: RewardType.Title, value: "Rap God", description: "Titre : Rap God", titleColor: TitleColor.Red }, icon: "🔥" },
  { id: 'mastery_fusion', name: "Alchimiste Musical", description: "Générer une chanson en mode Artiste en fusionnant avec au moins 3 styles additionnels.", tier: AchievementTier.Silver, category: AchievementCategory.Mastery, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 60, description: "60 Crédits" }, icon: "⚗️" },
  { id: 'mastery_unlock_all_bronze', name: "Collectionneur de Bronze", description: "Débloquer tous les succès de tier Bronze.", tier: AchievementTier.Gold, category: AchievementCategory.Mastery, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 200, description: "200 Crédits" }, icon: "🥉" },
  { id: 'mastery_unlock_all_silver', name: "Collectionneur d'Argent", description: "Débloquer tous les succès de tier Argent.", tier: AchievementTier.Diamond, category: AchievementCategory.Mastery, isSecret: false, target: 1, reward: { type: RewardType.Title, value: "Collectionneur d'Argent", description: "Titre : Collectionneur d'Argent", titleColor: TitleColor.Orange }, icon: "🥈" },
  { id: 'mastery_unlock_all_gold', name: "Collectionneur d'Or", description: "Débloquer tous les succès de tier Or.", tier: AchievementTier.Diamond, category: AchievementCategory.Mastery, isSecret: false, target: 1, reward: { type: RewardType.Title, value: "Collectionneur d'Or", description: "Titre : Collectionneur d'Or", titleColor: TitleColor.Gold }, icon: "🥇" },

  // --- Prestige --- 👑
  { id: 'prestige_ultimate_member', name: "Membre Ultimate", description: "Soutenir Lyr-IA en souscrivant au plan Ultimate.", tier: AchievementTier.Diamond, category: AchievementCategory.Prestige, isSecret: false, target: 1, reward: { type: RewardType.Title, value: "Mécène", description: "Titre : Mécène", titleColor: TitleColor.Gold }, icon: "💎" },
  { id: 'prestige_annual_member', name: "Vision à Long Terme", description: "Souscrire à n'importe quel plan annuel.", tier: AchievementTier.Gold, category: AchievementCategory.Prestige, isSecret: false, target: 1, reward: { type: RewardType.Credits, value: 150, description: "150 Crédits" }, icon: "📅" },

  // --- Secrets & Easter Eggs --- 🎁
  { id: 'secret_customize_theme', name: "Artiste Visuel", description: "Personnaliser le thème de couleurs de l'application.", tier: AchievementTier.Bronze, category: AchievementCategory.Exploration, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 15, description: "15 Crédits" }, icon: "🎨" },
  { id: 'secret_daft_punk_robot', name: "Technologic", description: "Générer une chanson de Daft Punk avec les traits 'Voix Vocoder' et 'Chant Robotique' activés.", tier: AchievementTier.Gold, category: AchievementCategory.Exploration, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 100, description: "100 Crédits" }, icon: "🤖" },
  { id: 'easter_egg_bohemian_rhapsody', name: "Is this the real life?", description: "Demander une certaine rhapsodie bohémienne.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" }, icon: "🎭" },
  { id: 'easter_egg_808s_heartbreak', name: "Heartless", description: "Générer une chanson sur un cœur brisé et une certaine boîte à rythmes.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" }, icon: "💔" },
  { id: 'easter_egg_master_of_puppets', name: "Master of Puppets", description: "Créer une structure personnalisée de 15 parties ou plus.", tier: AchievementTier.Gold, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 80, description: "80 Crédits" }, icon: "🎸" },
  { id: 'easter_egg_rhyme_orange', name: "Eminem serait fier", description: "Essayer de trouver une rime pour le mot 'orange'.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 40, description: "40 Crédits" }, icon: "🍊" },
  { id: 'easter_egg_all_about_the_hook', name: "Au Cœur du Refrain", description: "Créer une structure personnalisée composée uniquement de 4 refrains.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 25, description: "25 Crédits" }, icon: "🎵" },
  { id: 'easter_egg_acid_house', name: "Acid House", description: "Faire une requête rapide mentionnant les boîtes à rythmes TB-303 et TR-808/909.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" }, icon: "🔊" },
  { id: 'easter_egg_sound_check', name: "Sound Check", description: "Jouer frénétiquement avec le bouton 'Amplifier le Style Prompt'.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 20, description: "20 Crédits" , icon: "🔊" } },
  { id: 'easter_egg_studio_tour', name: "Studio Tour", description: "Visiter les onglets Générateur, Analyseur et Éditeur, puis revenir au Générateur.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 15, description: "15 Crédits" , icon: "🚪" } },
  { id: 'easter_egg_franco_viking', name: "Franco-Viking", description: "Générer une chanson de Vígundr en français.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "⚔️" } },
  { id: 'easter_egg_lofi_beats', name: "Lofi Beats to Relax/Study to", description: "Générer un instrumental Lo-fi, Chillwave et Jazz.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 30, description: "30 Crédits" , icon: "🎧" } },
  { id: 'easter_egg_konami_code', name: "↑↑↓↓←→←→BA", description: "Entrer un certain code secret très connu.", tier: AchievementTier.Gold, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 100, description: "100 Crédits" , icon: "🎮" } },
  { id: 'easter_egg_logo_spam', name: "Spammeur de Logo", description: "Cliquer sur le logo de manière un peu trop insistante.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 20, description: "20 Crédits" , icon: "🖱️" } },
  { id: 'easter_egg_sandwich', name: "sudo make me a sandwich", description: "Demander poliment un sandwich à l'IA.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 25, description: "25 Crédits" , icon: "🥪" } },
  { id: 'easter_egg_hidden_pixel', name: "Œil de Lynx", description: "Trouver et cliquer sur le pixel secret dans le guide.", tier: AchievementTier.Gold, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 150, description: "150 Crédits" , icon: "🔍" } },
  { id: 'easter_egg_over_9000', name: "IT'S OVER 9000!", description: "Faire une requête qui dépasse un certain niveau de puissance.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "💪" } },
  { id: 'easter_egg_all_your_base', name: "All Your Base Are Belong to Us", description: "Faire une référence à un classique de l'internet.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 25, description: "25 Crédits" , icon: "👾" } },
  { id: 'easter_egg_man_machine', name: "Mensch-Maschine", description: "Générer une chanson de Kraftwerk sur le thème de l'Homme-Machine.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "🤖" } },
  { id: 'easter_egg_theme_spammer', name: "Caméléon", description: "Changer de thème de couleur de manière compulsive.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 20, description: "20 Crédits" , icon: "🌈" } },
  { id: 'easter_egg_number_of_the_beast', name: "The Number of the Beast", description: "Demander à Iron Maiden une chanson sur un certain nombre.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "😈" } },
  { id: 'easter_egg_rickroll', name: "Never Gonna Give You Up", description: "Vous connaissez les règles, et moi aussi.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "🎵" } },
  
  // --- Nouveaux Easter Eggs (Culture Moderne) --- 🌐
  { id: 'easter_egg_spotify_wrapped', name: "Spotify Wrapped", description: "Générer une chanson mentionnant 'top songs' et 'year recap'.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "📊" } },
  { id: 'easter_egg_tiktok_viral', name: "Viral Hit", description: "Générer une chanson avec 'TikTok' et 'viral' dans le thème.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 40, description: "40 Crédits" , icon: "📱" } },
  { id: 'easter_egg_ai_takeover', name: "AI Overlords", description: "Demander à l'IA de générer une chanson sur l'IA qui prend le contrôle.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "🤖" } },
  { id: 'easter_egg_404', name: "Error 404: Lyrics Not Found", description: "Demander une chanson sur une erreur 404.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 25, description: "25 Crédits" , icon: "⚠️" } },
  { id: 'easter_egg_hello_world', name: "Hello World", description: "Générer une chanson mentionnant 'Hello World' (premier programme).", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 20, description: "20 Crédits" , icon: "👋" } },
  { id: 'easter_egg_matrix', name: "There Is No Spoon", description: "Générer une chanson Matrix avec 'red pill' ou 'blue pill'.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "💊" } },
  { id: 'easter_egg_winter_is_coming', name: "Winter Is Coming", description: "Générer une chanson Game of Thrones.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 30, description: "30 Crédits" , icon: "❄️" } },
  
  // --- Easter Eggs Séquences Mathématiques --- 🔢
  { id: 'easter_egg_fibonacci', name: "Séquence de Fibonacci", description: "Créer une structure avec 1,1,2,3,5,8 parties dans l'ordre.", tier: AchievementTier.Gold, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Title, value: "Mathématicien", description: "Titre : Mathématicien", titleColor: TitleColor.Blue , icon: "🔢" } },
  { id: 'easter_egg_pi_day', name: "π Day", description: "Générer une chanson le 14 mars (Pi Day) ou mentionnant π.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "🥧" } },
  { id: 'easter_egg_42', name: "Answer to Everything", description: "Générer exactement 42 chansons (référence Douglas Adams).", tier: AchievementTier.Diamond, category: AchievementCategory.EasterEgg, isSecret: true, target: 42, reward: { type: RewardType.Title, value: "Guide du Voyageur", description: "Titre : Guide du Voyageur", titleColor: TitleColor.Rainbow , icon: "📚" } },
  { id: 'easter_egg_666_beast_mode', name: "Beast Mode", description: "Avoir exactement 666 crédits à un moment donné.", tier: AchievementTier.Gold, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 66, description: "66 Crédits" , icon: "👹" } },
  
  // --- Easter Eggs Meta (Comportement) --- 🎮
  { id: 'easter_egg_night_owl', name: "Oiseau de Nuit", description: "Générer une chanson entre 2h et 5h du matin.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 40, description: "40 Crédits" , icon: "🦉" } },
  { id: 'easter_egg_speed_demon', name: "Speed Demon", description: "Générer 5 chansons en moins de 10 minutes.", tier: AchievementTier.Gold, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Title, value: "Producteur Express", description: "Titre : Producteur Express", titleColor: TitleColor.Red , icon: "💨" } },
  { id: 'easter_egg_perfectionist', name: "Perfectionniste", description: "Régénérer la même chanson 10 fois d'affilée.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "🎯" } },
  { id: 'easter_egg_delete_master', name: "Clean Freak", description: "Supprimer 20 chansons de votre historique.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 25, description: "25 Crédits" , icon: "🗑️" } },
  { id: 'easter_egg_hoarder', name: "Collectionneur Compulsif", description: "Avoir 100+ chansons dans votre historique sans en supprimer.", tier: AchievementTier.Gold, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Title, value: "Archiviste", description: "Titre : Archiviste", titleColor: TitleColor.Green , icon: "📦" } },
  
  // --- Easter Eggs Saisonniers --- 🎄
  { id: 'easter_egg_halloween', name: "Spooky Scary Skeletons", description: "Générer une chanson horror/halloween en octobre.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "🎃" } },
  { id: 'easter_egg_christmas', name: "All I Want For Christmas", description: "Générer une chanson de Noël en décembre.", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "🎄" } },
  { id: 'easter_egg_new_year', name: "Auld Lang Syne", description: "Générer une chanson le 31 décembre ou 1er janvier.", tier: AchievementTier.Gold, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 100, description: "100 Crédits" , icon: "🎆" } },
  { id: 'easter_egg_valentine', name: "Love Song Generator", description: "Générer une chanson d'amour le 14 février.", tier: AchievementTier.Bronze, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 30, description: "30 Crédits" , icon: "💝" } },
  { id: 'easter_egg_music_day', name: "Fête de la Musique", description: "Générer une chanson le 21 juin (Fête de la Musique).", tier: AchievementTier.Silver, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 50, description: "50 Crédits" , icon: "🎶" } },
  
  // --- Easter Eggs Ultra-Rares --- 💎
  { id: 'easter_egg_master_collector', name: "Maître Collectionneur", description: "Débloquer TOUS les Easter Eggs.", tier: AchievementTier.Diamond, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Title, value: "Chasseur d'Easter Eggs", description: "Titre : Chasseur d'Easter Eggs", titleColor: TitleColor.Rainbow , icon: "🏆" } },
  { id: 'easter_egg_lucky_777', name: "Jackpot", description: "Avoir exactement 777 crédits.", tier: AchievementTier.Gold, category: AchievementCategory.EasterEgg, isSecret: true, target: 1, reward: { type: RewardType.Credits, value: 77, description: "77 Crédits" , icon: "🎰" } },
  { id: 'easter_egg_1000_songs', name: "Maître Légendaire", description: "Générer 1000 chansons (accomplissement ultime).", tier: AchievementTier.Diamond, category: AchievementCategory.EasterEgg, isSecret: true, target: 1000, reward: { type: RewardType.Title, value: "Légende Immortelle", description: "Titre : Légende Immortelle", titleColor: TitleColor.Rainbow , icon: "⭐" } },
];
